[project]
name = "cftscal"
description = "Paradigms for running calibrations required for CFTS"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
license-files = ["LICENSE.txt"]
authors = [
    {name = "Brad Buran", email="buran@ohsu.edu"},
]
maintainers = [
    {name = "Brad Buran", email="buran@ohsu.edu"},
]
dependencies = [
    "cftsdata",
    "psiexperiment",
    "psiapp >= 0.0.7",
    "enaml >=0.13.0",
    "pyyaml",
    "tqdm",
]
dynamic = ["version"]

[project.optional-dependencies]
test = ["pytest"]

[project.scripts]
cfts-cal = "cftscal.main:main"

[tool.setuptools.packages.find]
include = ["cftscal*"]
namespaces = false

[tool.setuptools.package-data]
cftscal = [
    "resources/layout/*/*.layout",
    "resources/preferences/*/*.preferences",
    "icons/*.ico",
    "icons/*.png",
]

[tool.pytest.ini_options]
testpaths = ["tests"]

[build-system]
requires = ["setuptools>=77.0.0", "wheel", "setuptools_scm[toml]>=3.4.3"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "cftscal/version.py"
