'''
Stand-ins for the psiexperiment objects a paradigm's initialization
handler talks to.

A handler receives a workbench event and pulls the context and
controller plugins off it, so a test only needs objects with the same
handful of methods -- no running workbench, no hardware.
'''
import datetime as dt
import os


def set_env(**kwargs):
    '''
    Set environment variables for the handler under test. Used with the
    `event` fixture, which swaps in an empty environment first.
    '''
    os.environ.update(kwargs)


class FakeItem:
    '''
    Stands in for a psi context item (a `Parameter`/`EnumParameter`).
    '''

    def __init__(self):
        self.expression = None
        self.value = None
        self.editable = True

    def set_value(self, value):
        self.value = value


class FakeContext:

    def __init__(self):
        self.items = {}

    def get_item(self, name):
        return self.items.setdefault(name, FakeItem())


class FakeChannel:

    def __init__(self, label=''):
        self.calibration = None
        self.gain = None
        self.label = label


class FakeController:

    def __init__(self):
        self.channels = {}

    def get_channel(self, name):
        # Labeled the way psi labels a channel whose IO manifest gives it no
        # label of its own: 'hw_ai::input_1' -> 'Input 1'.
        label = name.split('::')[-1].replace('_', ' ').capitalize()
        return self.channels.setdefault(name, FakeChannel(label))


class FakeWorkbench:

    def __init__(self):
        self.plugins = {
            'psi.context': FakeContext(),
            'psi.controller': FakeController(),
        }

    def get_plugin(self, name):
        return self.plugins[name]


class FakeEvent:

    def __init__(self):
        self.workbench = FakeWorkbench()

    @property
    def context(self):
        return self.workbench.plugins['psi.context']

    @property
    def controller(self):
        return self.workbench.plugins['psi.controller']


class FakeCalibration:
    '''
    Stands in for a `cftscal.objects.Calibration`: it knows its name and
    when it was measured, and `load` returns the psiaudio calibration
    that gets assigned to the channel.
    '''

    #: Date every fake calibration reports, so tests can assert on the
    #: text built from it.
    DATETIME = dt.datetime(2025, 6, 12, 9, 30)

    def __init__(self, string):
        self.name = string
        self.datetime = self.DATETIME

    def load(self):
        return f'calibration for {self.name}'


class FakeManager:
    '''
    Stands in for one of the calibration managers in `cftscal.objects`.
    `from_string` normally parses a string generated by cftscal and
    returns the calibration it names.
    '''

    def __init__(self):
        self.loaded = None

    def from_string(self, string):
        self.loaded = string
        return FakeCalibration(string)
